import Categories from "./pageshome/Categories";
import Hero from "./pageshome/Hero";
import Ourproducts from "./pageshome/ourproducts/Ourproducts";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="h-screen w-full">
      <Hero/>
      <Categories/>
      <Ourproducts/>
    </div>
  );
}
